---
# tasks file for ansible-irssi

- name: Install irssi
  become: yes
  package:
    name: irssi
    state: present
  tags:
    - install

- name: Create irssi directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ irssi_user }}"
    group: "{{ irssi_group }}"
  with_items:
    - "{{ irssi_directory }}"
    - "{{ irssi_directory_config }}"
    - "{{ irssi_directory_scripts }}"
  tags:
    - install

- name: Configure irssi
  become: yes
  template:
    src: config.j2
    dest: "{{ irssi_directory_config }}"
    owner: "{{ irssi_user }}"
    group: "{{ irssi_group }}"
  tags:
    - configuration
